#Файл конфигурации
#Выглядит круто


MESSAGES:
  CFG_RELOADED_SUCESSFULLY: '&a&lКонфигурация плагина успешно перезагружена!'
  GAME_START_5_MINUTES: '&eИгра начнётся через &65&e минут!'
  GAME_START_5_SECONDS: '&eИгра начнётся через &65&e секунд!'
  NO_DROP: '&eУпс! Дропа нет :('
  RESPAWNED: '&eТы возродился в последний раз.'
  RESPAWNED_WITH_LOOT: '&eТы возродился с послесмертным набором в инвентаре.'
  RESPAWNED_WITH_LOOT_LAST: '&eТы возродился с послесмертным набором в инвентаре в последний раз.'
  STARTED: '&fИгра началась. Ширина границы - &61000 блоков&f.%new%&eДо следующего сужения 60 минут!'
  READY: '&fПриготовтесь! Игра начнётся через &e10&f секунд.'
  WINNER_IS: '&eИгра закончилась. Победитель - &e'
  GAME_GOING: '&eИгра уже идёт... &6Дождитесь её окончания'
  PVP_ON: '&eРежим PVP включён!'